var DATA = [
      { id:0, label:"com.tencent.recommendspot", link:"com/tencent/recommendspot/package-summary.html", type:"package" },
      { id:1, label:"com.tencent.recommendspot.TMMRBDataManager", link:"com/tencent/recommendspot/TMMRBDataManager.html", type:"class" },
      { id:2, label:"com.tencent.recommendspot.TMMRBDataManager.TMMAttachRecommendSpotListener", link:"com/tencent/recommendspot/TMMRBDataManager.TMMAttachRecommendSpotListener.html", type:"class" },
      { id:3, label:"com.tencent.recommendspot.TMMRBDataManager.TMMRecommendedBoardListener", link:"com/tencent/recommendspot/TMMRBDataManager.TMMRecommendedBoardListener.html", type:"class" },
      { id:4, label:"com.tencent.recommendspot.TMMRBDataManager.TMMSubHubListener", link:"com/tencent/recommendspot/TMMRBDataManager.TMMSubHubListener.html", type:"class" },
      { id:5, label:"com.tencent.recommendspot.TMMRBDataManager.TMMTransportationHubListener", link:"com/tencent/recommendspot/TMMRBDataManager.TMMTransportationHubListener.html", type:"class" },
      { id:6, label:"com.tencent.recommendspot.TMMRecommendedBoardManager", link:"com/tencent/recommendspot/TMMRecommendedBoardManager.html", type:"class" },
      { id:7, label:"com.tencent.recommendspot.TMMRecommendedBoardManager.TMMPointAnimaListener", link:"com/tencent/recommendspot/TMMRecommendedBoardManager.TMMPointAnimaListener.html", type:"class" },
      { id:8, label:"com.tencent.recommendspot.TMMRecommendedBoardManager.TMMRecommendedBoardManagerConfig", link:"com/tencent/recommendspot/TMMRecommendedBoardManager.TMMRecommendedBoardManagerConfig.html", type:"class" },
      { id:9, label:"com.tencent.recommendspot.TMMRecommendedBoardManager.TMMRecommendedBoardOption", link:"com/tencent/recommendspot/TMMRecommendedBoardManager.TMMRecommendedBoardOption.html", type:"class" },
      { id:10, label:"com.tencent.recommendspot.TMMRecommendedBoardManager.TMMUIStyle", link:"com/tencent/recommendspot/TMMRecommendedBoardManager.TMMUIStyle.html", type:"class" },
      { id:11, label:"com.tencent.recommendspot.recospot.bean", link:"com/tencent/recommendspot/recospot/bean/package-summary.html", type:"package" },
      { id:12, label:"com.tencent.recommendspot.recospot.bean.RecommendSpotInfo", link:"com/tencent/recommendspot/recospot/bean/RecommendSpotInfo.html", type:"class" },
      { id:13, label:"com.tencent.recommendspot.recospot.bean.TMMLatlng", link:"com/tencent/recommendspot/recospot/bean/TMMLatlng.html", type:"class" },
      { id:14, label:"com.tencent.recommendspot.recospot.bean.TMMRecommendSpotBean", link:"com/tencent/recommendspot/recospot/bean/TMMRecommendSpotBean.html", type:"class" },
      { id:15, label:"com.tencent.recommendspot.recospot.bean.TMMRecommendSpotBean.BoardingPointBean", link:"com/tencent/recommendspot/recospot/bean/TMMRecommendSpotBean.BoardingPointBean.html", type:"class" },
      { id:16, label:"com.tencent.recommendspot.recospot.bean.TMMRecommendSpotBean.BoardingPointBean.LocationBean", link:"com/tencent/recommendspot/recospot/bean/TMMRecommendSpotBean.BoardingPointBean.LocationBean.html", type:"class" },
      { id:17, label:"com.tencent.recommendspot.recospot.bean.TMMSubTraHubBean", link:"com/tencent/recommendspot/recospot/bean/TMMSubTraHubBean.html", type:"class" },
      { id:18, label:"com.tencent.recommendspot.recospot.bean.TMMSubTraHubBean.DataBeanX", link:"com/tencent/recommendspot/recospot/bean/TMMSubTraHubBean.DataBeanX.html", type:"class" },
      { id:19, label:"com.tencent.recommendspot.recospot.bean.TMMSubTraHubBean.DataBeanX.DetailBean", link:"com/tencent/recommendspot/recospot/bean/TMMSubTraHubBean.DataBeanX.DetailBean.html", type:"class" },
      { id:20, label:"com.tencent.recommendspot.recospot.bean.TMMSubTraHubBean.DataBeanX.DetailBean.DataBean", link:"com/tencent/recommendspot/recospot/bean/TMMSubTraHubBean.DataBeanX.DetailBean.DataBean.html", type:"class" },
      { id:21, label:"com.tencent.recommendspot.recospot.bean.TMMSubTraHubBean.DataBeanX.DetailBean.DataBean.LocationBean", link:"com/tencent/recommendspot/recospot/bean/TMMSubTraHubBean.DataBeanX.DetailBean.DataBean.LocationBean.html", type:"class" },
      { id:22, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.html", type:"class" },
      { id:23, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.html", type:"class" },
      { id:24, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.html", type:"class" },
      { id:25, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean.TraHubBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.html", type:"class" },
      { id:26, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean.html", type:"class" },
      { id:27, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean.HitTraHubBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean.HitTraHubBean.html", type:"class" },
      { id:28, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean.HitTraHubBean.LocationBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.HitSubFenceBean.HitTraHubBean.LocationBean.html", type:"class" },
      { id:29, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.SubFenceBean", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubBean.TraObjBean.DetailBean.TraHubBean.SubFenceBean.html", type:"class" },
      { id:30, label:"com.tencent.recommendspot.recospot.bean.TMMTraHubModel", link:"com/tencent/recommendspot/recospot/bean/TMMTraHubModel.html", type:"class" },
      { id:31, label:"com.tencent.recommendspot.ui", link:"com/tencent/recommendspot/ui/package-summary.html", type:"package" },
      { id:32, label:"com.tencent.recommendspot.ui.PointMarkerView", link:"com/tencent/recommendspot/ui/PointMarkerView.html", type:"class" }

    ];
